name: Run parcels benchmarks

on:
  repository_dispatch:
    types: [run-parcels-benchmarks]

jobs:
  publish-commit:
    permissions:
      contents: 'read'
      pages: write
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout parcels repo
        uses: actions/checkout@v4
        with:
          repository: oceanparcels/parcels
          ref: asv
          fetch-depth: 0
          path: parcels_bm_run

      - name: Set up conda environment
        uses: mamba-org/setup-micromamba@v2
        with:
          micromamba-version: "1.5.10-0"
          environment-name: parcels-dev
          cache-environment: true
          cache-environment-key: "${{runner.os}}-${{runner.arch}}-py${{env.PYTHON_VERSION}}-${{env.TODAY}}-${{hashFiles(env.CONDA_ENV_FILE)}}-benchmark"
          create-args: >-
            python-build
            asv
            mamba<=1.5.10

      - name: Run benchmarks
        shell: bash -l {0}
        id: benchmark
        env:
          OPENBLAS_NUM_THREADS: 1
          MKL_NUM_THREADS: 1
          OMP_NUM_THREADS: 1
          ASV_FACTOR: 1.5
          ASV_SKIP_SLOW: 1
        run: |
          set -x
          cd parcels_bm_run/asv_bench
          asv machine --yes
          asv run

      - name: Publish benchmarks to HTML
        run: |
          mkdir public
          cd parcels_bm_run/asv_bench
          asv publish --html-dir ../../public

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'public/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
