name: Run parcels benchmarks

on:
  repository_dispatch:
    types: [run-parcels-benchmarks]

jobs:
  publish-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout parcels repo
        uses: actions/checkout@v3
        with:
          repository: https://github.com/oceanparcels/parcels.git
          ref: main
      - name: Do something in the repo and store results
        run: |
          mkdir public
          git log -1 --pretty=format:'%H' > public/result.txt

      - name: Setup Pages action
        uses: actions/setup-pages@v3

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
